server:
  port: 8082

mybatis-plus:
  mapper-locations: classpath:sql/*.xml
  config-location: classpath:mybatis-config.xml

ding:
  talk:
    secret: 333333333333333333333333333333333333333333
    token: https://oapi.dingtalk.com/robot/send?access_token=333333333333

spring:
  datasource:
    url: jdbc:mysql://172.18.21.110:3306/js_etc?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&rewriteBatchedStatements=true
    username: 666666
    password: 888888888888
  redis:
    database: 0
    host: 172.18.21.111
    port: 6379
    password: 999999999
    prefix: 777777
    timeout: 10000



sora:
  start: true
  mysql:
    hosts:
    - name: faxin
      host: 172.18.21.110
      port: 3306
      username: 9999999
      password: 8888899
      filename: mysql-bin.006950
      position: 106514948
      sequel: false            #是否断点续传
      timeOffset: -28800000    #时间位移

      database:
      - name: js_etc
        watch:   #处理类:对应表名
          TestUserWatcher: test_user
